# Generated by Django 5.2.12 on 2026-03-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaterSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=50)),
                ('collection_date', models.DateTimeField()),
                ('collector_name', models.CharField(max_length=100)),
                ('sample_type', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('temperature', models.FloatField()),
                ('ph', models.FloatField()),
                ('turbidity', models.FloatField()),
                ('conductivity', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
